package constants

var (
	DATABASE_HOST     = "DATABASE_HOST"
	DATABASE_NAME     = "DATABASE_NAME"
	DATABASE_USER     = "DATABASE_USER"
	DATABASE_PASSWORD = "DATABASE_PASSWORD"
	DATABASE_SSL_MODE = "DATABASE_SSL_MODE"
	JWT_SIGNING_KEY   = "JWT_SIGNING_KEY"
	REDIS_HOST        = "REDIS_HOST"
	REDIS_PASSWORD    = "REDIS_PASSWORD"
)