version: "3"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  database:
    image: postgres:14.1-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - zappr
  redis:
    image: "bitnami/redis:latest"
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - zappr
  zappr:
    container_name: zappr
    restart: on-failure
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      - ZAPPR_POSTGRES_PASSWORD
      - ZAPPR_POSTGRES_USER
      - ZAPPR_POSTGRES_DB
      - ZAPPR_POSTGRES_HOST
      - JWT_SIGNING_KEY
    depends_on:
      - redis
      - database
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; ./Zappr'
    networks:
      - zappr

networks:
  zappr:

volumes:
  caddy_data:
  caddy_config:
  db:
