version: "3"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - zappr
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  zappr:
    container_name: zappr
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      - ZAPPR_POSTGRES_PASSWORD
      - ZAPPR_POSTGRES_USER
      - ZAPPR_POSTGRES_DB
      - ZAPPR_POSTGRES_HOST
      - JWT_SIGNING_KEY
    depends_on:
      - redis
    links:
      - redis
    networks:
      - zappr

  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - zappr

networks:
  zappr:

volumes:
  caddy_data:
  caddy_config:
