version: "3"

services:
  zappr:
    container_name: zappr
    build:
      context: .
    ports:
      - "9000:9000"
    networks:
      - zappr
    volumes:
      - zappr:/app:rw

  postgres:
    container_name: postgres
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=zappr_pg_local@zappr-local
      - POSTGRES_PASSWORD=p@$$w0rd
      - POSTGRES_DB=zappr
      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  zappr:
  postgres:

volumes:
  zappr:
  postgres:
