version: "3"

services:
  zappr:
    container_name: zappr
    build:
      context: .
    ports:
      - "9000:9000"
    networks:
      - zappr
    environment:
      - ZAPPR_POSTGRES_PASSWORD=Passw0rdtechnovert
      - ZAPPR_POSTGRES_USER=zappr_pg_local@zappr-local
      - ZAPPR_POSTGRES_DB=zappr
      - ZAPPR_POSTGRES_HOST=zappr-local.postgres.database.azure.com
      - JWT_SIGNING_KEY=xTWX3hql42

  postgres:
    container_name: postgres
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=zappr
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  zappr:
  postgres:

volumes:
  zappr:
  postgres:
