version: "3"

services:
  zappr:
    container_name: zappr
    build:
      context: .
    ports:
      - "9000:9000"
    networks:
      - zappr
    environment:
      - ZAPPR_POSTGRES_PASSWORD
      - ZAPPR_POSTGRES_USER
      - ZAPPR_POSTGRES_DB
      - ZAPPR_POSTGRES_HOST
      - JWT_SIGNING_KEY

  redis-master:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE
      - REDIS_PASSWORD

  redis-replica:
    image: "bitnami/redis:latest"
    ports:
      - "6379"
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE
      - REDIS_MASTER_HOST
      - REDIS_MASTER_PORT_NUMBER
      - REDIS_MASTER_PASSWORD
      - REDIS_PASSWORD

networks:
  zappr:

volumes:
  zappr:
